---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: testapiserver-allow-egress-api
specs:
  - description: "Allow egress to testapibackendsvc from testapiserver"
    endpointSelector:
      matchLabels:
        app: testapiserver
    egress:
      - toEndpoints:
          - matchLabels:
              io.kubernetes.pod.namespace: kube-system
              k8s-app: kube-dns
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
            rules:
              dns:
                - matchPattern: "*"
      - toServices:
          - k8sService:
              serviceName: testapibackendsvc
              namespace: assignment
        toPorts:
          - ports:
              - port: "10000"
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: testapiserver-allow-ingress-www
specs:
  - description: "Allow ingress to testapiserver from ingress"
    endpointSelector:
      matchLabels:
        app: testapiserver
    ingress:
      - fromEntities:
        - world
        toPorts:
          - ports:
              - port: "8080"
