---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: testapiserver-allow-egress-api
specs:
  - description: "Allow egress to testapibackendsvc from testapiserver"
    endpointSelector:
      matchLabels:
        app: testapiserver
    egress:
      - toServices:
          - k8sServiceSelector:
              selector:
                matchLabels:
                  name: testapibackendsvc
              namespace: assignment
        toPorts:
          - ports:
              - port: "10000"
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: testapiserver-allow-ingress-www
specs:
  - description: "Allow ingress to testapiserver from ingress"
    endpointSelector:
      matchLabels:
        app: testapiserver
    ingress:
      - fromEndpoints:
        - matchLabels:
            role: frontend
