---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: testapiserver-allow-egress-api
specs:
  - description: "Allow egress to testapibackendsvc from testapiserver"
    endpointSelector:
      matchLabels:
        app: testapiserver
    egress:
      - toEndpoints:
          - matchLabels:
              app: testapibackendsvc
        toPorts:
          - ports:
              - port: "10000"
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: testapiserver-allow-ingress-www
specs:
  - description: "Allow ingress to testapiserver from ingress"
    endpointSelector:
      matchLabels:
        app: testapiserver
    ingress:
      - fromEntities:
        - world
        toPorts:
          - ports:
              - port: "8080"
