---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testapiserver-ingress
spec:
  ingressClassName: traefik
  type: ClusterIP
  rules:
    - http:
        paths:
          - path: /testapiserver
            pathType: Prefix
            backend:
              service:
                name: testapiserversvc
                port:
                  number: 8080
