---
apiVersion: v1
kind: Service
metadata:
  name: testapiserversvc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
    - port: 8080
  selector:
    app: testapiserver
