argocd-apps:
  projects:
    - name: assignment
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'

  applications:
    - name: namepspaces
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      project: system
      destination:
        name: in-cluster
        namespace: argocd
      source:
        repoURL: https://github.com/frealmyr/containers-assignment-apps
        targetRevision: main
        path: namespaces
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
      additionalAnnotations:
        argocd.argoproj.io/sync-wave: "-1"

    - name: test-api
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      project: assignment
      destination:
        name: in-cluster
        namespace: assignment
      source:
        repoURL: https://github.com/frealmyr/containers-assignment-apps
        targetRevision: main
        path: applications/test-api
      syncPolicy:
        automated:
          prune: true
          selfHeal: false

    - name: test-api-server
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      project: assignment
      destination:
        name: in-cluster
        namespace: assignment
      source:
        repoURL: https://github.com/frealmyr/containers-assignment-apps
        targetRevision: main
        path: applications/test-api-server
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
