argocd-apps:

  projects:
    - name: assignment
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'

  applications:
    - name: test-api
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      project: assignment
      destination:
        name: in-cluster
        namespace: assignment
      source:
        repoURL: https://github.com/frealmyr/containers-assignment-apps
        targetRevision: main
        path: applications/test-api
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true

    - name: test-api-server
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      project: assignment
      destination:
        name: in-cluster
        namespace: assignment
      source:
        repoURL: https://github.com/frealmyr/containers-assignment-apps
        targetRevision: main
        path: applications/test-api-server
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
